#include"twj.h"
uint code cw[]={0x09,0x01,0x03,0x02,0x06,0x04,0x0c,0x08};
uint code ccw[]={0x08,0x0c,0x04,0x06,0x02,0x03,0x01,0x09};
void main()
{
    uchar g,i;
    BULLE=1;
    RED=0;
    P0=0xff;
    delay(10);
    lcd_csh();
    delay(10);
    lcd_w_cmd(0x80);
    lcd_w_dat('L');
    lcd_w_cmd(0x87);
    lcd_w_dat('G');
    lcd_w_cmd(0xC0);
    lcd_w_dat('T');
    lcd_w_cmd(0xC5);
    lcd_w_dat(0xdf);
    lcd_w_dat('C');
    lcd_w_cmd(0x85);
    lcd_w_dat('\%');
    lcd_w_cmd(0x8C);
    lcd_w_dat('\%');
    lcd_w_cmd(0xC8);
    lcd_w_dat('M');
    lcd_w_cmd(0xC9);
    lcd_w_dat('0');
    lcd_w_cmd(0x8E);
    lcd_w_dat('F');
    lcd_w_cmd(0x8F);
    lcd_w_dat('0');
    lcd_w_cmd(0xCB);
    lcd_w_dat('1');
    lcd_w_cmd(0xCC);
    lcd_w_dat('1');
    lcd_w_cmd(0xCE);
    lcd_w_dat('4');
    lcd_w_cmd(0xCF);
    lcd_w_dat('5');
    delay(10);
        while (1)
        {
            BULLE=1;
            RED=0;
            lcd_w_cmd(0x81);
            delay(10);
            initialize();
            adc_GM();
            xianshi_GM();
            for(g=1;g<5;g++)
            {
                lcd_w_dat(temp_ADC[g]);
                delay(10);
            }
            lcd_w_cmd(0x88);
            delay(10);
            initialize();
            adc_MQ2();
            xianshi_MQ2();
            for(g=1;g<5;g++)
            {
                lcd_w_dat(temp_ADC[g]);
                delay(10);
            }
            ds18b20_readtemp();
            Temperature_Convert();
            lcd_w_cmd(0xC1);
            delay(10);
            for(g=0;g<4;g++)
            {
                lcd_w_dat(temp_DS18B20[g]);
                delay(10);
            }
            if(temperature<=300&&num_MQ2<=200)
            {
                lcd_w_cmd(0x8F);
                lcd_w_dat('0');
            }
            if(num_GM>800||num_MQ2>200||temperature>300)
            {
                RED=1;
                BULLE=0;
                lcd_w_cmd(0xC9);
                lcd_w_dat('1');
                for(i=0;i<64;i++)
                { 
                for(g=0;g<8;g++)
                {
                    P3=cw[g];
                    BB=1;
                    delay(300);
                    BB=0;
                    delay(300);
                }
                }
                if(temperature>300)
                {
                    lcd_w_cmd(0x8F);
                    lcd_w_dat('T');

                }
                if(num_MQ2>200)
                {
                    lcd_w_cmd(0x8F);
                    lcd_w_dat('G');

                }
                P3=0X00;
            }
            else if(num_GM<=800&&num_MQ2<=200&&temperature<=300&&num_GM>=300)
            {
                lcd_w_cmd(0xC9);
                lcd_w_dat('0');
            }
            else if(num_GM<300)
            {
                RED=1;
                BULLE=0;
                lcd_w_cmd(0xC9);
                lcd_w_dat('2');
                for(i=0;i<64;i++)
                { 
                for(g=0;g<8;g++)
                {
                    P3=ccw[g];
                    BB=1;
                    delay(300);
                    BB=0;
                    delay(300);
                }
                }
                P3=0X00;
            }
            else
            delay(1);
        }
}